### ISSUE TITLE
training compute

### ISSUE THREAD

**Issue by pengzhangzhi** [liusulin/DDPD#1]
Hey,

Based on the appendix, this code for text8 takes 4 days on 4A100s?

**Comment by liusulin** [comment]
Hi, yes. On text8, we followed experiment setting of https://github.com/andrew-cr/discrete_flow_models/tree/main, and training denoiser for 750k iterations with batch size 2048 requires 3~4 days. We trained the planner for 450k iterations and find it to be sufficient.
